In [519]:
import pandas as pd 
import numpy as np
from scipy import stats as s
import cv2
import math

In [520]:
tot_kill = pd.DataFrame()
tot_death = pd.DataFrame()

for i in range(1,501):
    tot_kill = tot_kill.append({'videos': 'frame_kill_'+str(i)+'.jpg'}, ignore_index=True)
    tot_death = tot_death.append({'videos': 'frame_death_'+str(i)+'.jpg'}, ignore_index=True)
        
tot_kill['label_kill'] = 1
tot_kill['label_death'] = 0
tot_death['label_kill'] = 0
tot_death['label_death'] = 1

In [521]:
tot_kill = tot_kill.sample(frac = 1)

In [522]:
tot_death

                  videos  label_kill  label_death
0      frame_death_1.jpg           0            1
1      frame_death_2.jpg           0            1
2      frame_death_3.jpg           0            1
3      frame_death_4.jpg           0            1
4      frame_death_5.jpg           0            1
..                   ...         ...          ...
495  frame_death_496.jpg           0            1
496  frame_death_497.jpg           0            1
497  frame_death_498.jpg           0            1
498  frame_death_499.jpg           0            1
499  frame_death_500.jpg           0            1

[500 rows x 3 columns]

In [523]:
tot_kill

                 videos  label_kill  label_death
462  frame_kill_463.jpg           1            0
402  frame_kill_403.jpg           1            0
487  frame_kill_488.jpg           1            0
190  frame_kill_191.jpg           1            0
235  frame_kill_236.jpg           1            0
..                  ...         ...          ...
257  frame_kill_258.jpg           1            0
409  frame_kill_410.jpg           1            0
457  frame_kill_458.jpg           1            0
422  frame_kill_423.jpg           1            0
344  frame_kill_345.jpg           1            0

[500 rows x 3 columns]

In [524]:
train_set_kill = tot_kill[:300]
train_set_death = tot_death[:300]

train_set = train_set_kill.append(train_set_death, ignore_index=True)
train_set

                  videos  label_kill  label_death
0     frame_kill_463.jpg           1            0
1     frame_kill_403.jpg           1            0
2     frame_kill_488.jpg           1            0
3     frame_kill_191.jpg           1            0
4     frame_kill_236.jpg           1            0
..                   ...         ...          ...
595  frame_death_296.jpg           0            1
596  frame_death_297.jpg           0            1
597  frame_death_298.jpg           0            1
598  frame_death_299.jpg           0            1
599  frame_death_300.jpg           0            1

[600 rows x 3 columns]

In [525]:
train_set  = train_set .sample(frac = 1)
train_set

                  videos  label_kill  label_death
215   frame_kill_193.jpg           1            0
75    frame_kill_202.jpg           1            0
150   frame_kill_317.jpg           1            0
534  frame_death_235.jpg           0            1
141   frame_kill_254.jpg           1            0
..                   ...         ...          ...
333   frame_death_34.jpg           0            1
339   frame_death_40.jpg           0            1
259   frame_kill_302.jpg           1            0
81    frame_kill_301.jpg           1            0
230   frame_kill_122.jpg           1            0

[600 rows x 3 columns]

In [526]:
y_train =  train_set[['label_kill', 'label_death']]
y_train

     label_kill  label_death
215           1            0
75            1            0
150           1            0
534           0            1
141           1            0
..          ...          ...
333           0            1
339           0            1
259           1            0
81            1            0
230           1            0

[600 rows x 2 columns]

In [527]:
val_set_kill = tot_kill.iloc[300:400]
val_set_death = tot_death.iloc[300:400]

val_set = val_set_kill.append(val_set_death, ignore_index=True)
val_set

                  videos  label_kill  label_death
0      frame_kill_44.jpg           1            0
1     frame_kill_149.jpg           1            0
2     frame_kill_270.jpg           1            0
3     frame_kill_204.jpg           1            0
4     frame_kill_406.jpg           1            0
..                   ...         ...          ...
195  frame_death_396.jpg           0            1
196  frame_death_397.jpg           0            1
197  frame_death_398.jpg           0            1
198  frame_death_399.jpg           0            1
199  frame_death_400.jpg           0            1

[200 rows x 3 columns]

In [528]:
val_set  = val_set .sample(frac = 1)
val_set

                  videos  label_kill  label_death
78    frame_kill_123.jpg           1            0
20    frame_kill_102.jpg           1            0
161  frame_death_362.jpg           0            1
57    frame_kill_166.jpg           1            0
73     frame_kill_93.jpg           1            0
..                   ...         ...          ...
171  frame_death_372.jpg           0            1
54    frame_kill_299.jpg           1            0
121  frame_death_322.jpg           0            1
158  frame_death_359.jpg           0            1
89    frame_kill_274.jpg           1            0

[200 rows x 3 columns]

In [529]:
y_val =  val_set[['label_kill', 'label_death']]
y_val

     label_kill  label_death
78            1            0
20            1            0
161           0            1
57            1            0
73            1            0
..          ...          ...
171           0            1
54            1            0
121           0            1
158           0            1
89            1            0

[200 rows x 2 columns]

In [530]:
test_set_kill = tot_kill.iloc[400:500]
test_set_death = tot_death.iloc[400:500]

test_set = test_set_kill.append(test_set_death, ignore_index=True)
test_set

                  videos  label_kill  label_death
0      frame_kill_16.jpg           1            0
1     frame_kill_212.jpg           1            0
2      frame_kill_27.jpg           1            0
3     frame_kill_378.jpg           1            0
4     frame_kill_468.jpg           1            0
..                   ...         ...          ...
195  frame_death_496.jpg           0            1
196  frame_death_497.jpg           0            1
197  frame_death_498.jpg           0            1
198  frame_death_499.jpg           0            1
199  frame_death_500.jpg           0            1

[200 rows x 3 columns]

In [531]:
test_set  = test_set .sample(frac = 1)
test_set

                  videos  label_kill  label_death
182  frame_death_483.jpg           0            1
19    frame_kill_393.jpg           1            0
49    frame_kill_497.jpg           1            0
59    frame_kill_230.jpg           1            0
96    frame_kill_410.jpg           1            0
..                   ...         ...          ...
187  frame_death_488.jpg           0            1
68    frame_kill_291.jpg           1            0
163  frame_death_464.jpg           0            1
85      frame_kill_1.jpg           1            0
116  frame_death_417.jpg           0            1

[200 rows x 3 columns]

In [532]:
y_test =  test_set[['label_kill', 'label_death']]
y_test

     label_kill  label_death
182           0            1
19            1            0
49            1            0
59            1            0
96            1            0
..          ...          ...
187           0            1
68            1            0
163           0            1
85            1            0
116           0            1

[200 rows x 2 columns]

In [3]:
def train_val_test_set():
    tot_kill = pd.DataFrame()
    tot_death = pd.DataFrame()

    for i in range(1,501):
        tot_kill = tot_kill.append({'videos': 'frame_kill_'+str(i)+'.jpg'}, ignore_index=True)
        tot_death = tot_death.append({'videos': 'frame_death_'+str(i)+'.jpg'}, ignore_index=True)

    tot_kill['label'] = 1
    tot_death['label'] = 0
    
    train_set_kill = tot_kill[:300]
    train_set_death = tot_death[:300]
    train_set = train_set_kill.append(train_set_death, ignore_index=True)
    
    val_set_kill = tot_kill.iloc[300:400]
    val_set_death = tot_death.iloc[300:400]
    val_set = val_set_kill.append(val_set_death, ignore_index=True)
    
    test_set_kill = tot_kill.iloc[400:500]
    test_set_death = tot_death.iloc[400:500]
    test_set = test_set_kill.append(test_set_death, ignore_index=True)
    
    return train_set, val_set, test_set

In [4]:
train_set, val_set, test_set = train_val_test_set()

In [413]:
for video_name in train_set['videos']:
    print(video_name)

frame_death_80.jpg
frame_death_92.jpg
frame_death_39.jpg
frame_kill_35.jpg
frame_death_252.jpg
frame_kill_73.jpg
frame_kill_234.jpg
frame_kill_42.jpg
frame_kill_12.jpg
frame_death_73.jpg
frame_kill_153.jpg
frame_death_259.jpg
frame_death_298.jpg
frame_death_112.jpg
frame_death_156.jpg
frame_death_129.jpg
frame_kill_281.jpg
frame_death_246.jpg
frame_death_126.jpg
frame_death_89.jpg
frame_death_105.jpg
frame_death_95.jpg
frame_kill_299.jpg
frame_death_188.jpg
frame_kill_283.jpg
frame_death_94.jpg
frame_kill_268.jpg
frame_kill_113.jpg
frame_death_122.jpg
frame_kill_196.jpg
frame_death_293.jpg
frame_kill_263.jpg
frame_death_118.jpg
frame_kill_14.jpg
frame_death_37.jpg
frame_kill_247.jpg
frame_kill_183.jpg
frame_kill_32.jpg
frame_death_264.jpg
frame_kill_255.jpg
frame_death_179.jpg
frame_kill_238.jpg
frame_kill_116.jpg
frame_death_186.jpg
frame_death_31.jpg
frame_death_123.jpg
frame_death_211.jpg
frame_kill_58.jpg
frame_kill_108.jpg
frame_death_241.jpg
frame_kill_44.jpg
frame_kill_101.jpg
frame_death_227.jpg
frame_death_238.jpg
frame_death_254.jpg
frame_kill_259.jpg
frame_kill_169.jpg
frame_death_78.jpg
frame_kill_64.jpg
frame_death_275.jpg
frame_death_193.jpg
frame_kill_133.jpg
frame_death_23.jpg
frame_kill_174.jpg
frame_kill_290.jpg
frame_death_87.jpg
frame_death_145.jpg
frame_kill_9.jpg
frame_death_176.jpg
frame_death_168.jpg
frame_kill_184.jpg
frame_kill_15.jpg
frame_death_219.jpg
frame_death_195.jpg
frame_death_62.jpg
frame_kill_25.jpg
frame_death_84.jpg
frame_death_296.jpg
frame_death_8.jpg
frame_death_217.jpg
frame_kill_96.jpg
frame_death_58.jpg
frame_kill_185.jpg
frame_kill_291.jpg
frame_kill_177.jpg
frame_death_103.jpg
frame_death_34.jpg
frame_kill_55.jpg
frame_kill_176.jpg
frame_kill_90.jpg
frame_kill_145.jpg
frame_death_47.jpg
frame_kill_260.jpg
frame_death_274.jpg
frame_kill_276.jpg
frame_kill_61.jpg
frame_death_21.jpg
frame_kill_208.jpg
frame_kill_122.jpg
frame_kill_274.jpg
frame_death_45.jpg
frame_kill_282.jpg
frame_kill_191.jpg
frame_kill_147.jpg
frame_death_35.jpg
frame_kill_93.jpg
frame_kill_149.jpg
frame_death_24.jpg
frame_kill_52.jpg
frame_kill_166.jpg
frame_death_27.jpg
frame_kill_257.jpg
frame_kill_49.jpg
frame_death_232.jpg
frame_kill_100.jpg
frame_kill_216.jpg
frame_kill_261.jpg
frame_kill_5.jpg
frame_kill_155.jpg
frame_kill_77.jpg
frame_death_76.jpg
frame_death_163.jpg
frame_kill_178.jpg
frame_death_33.jpg
frame_death_166.jpg
frame_death_5.jpg
frame_kill_54.jpg
frame_kill_246.jpg
frame_kill_253.jpg
frame_death_185.jpg
frame_death_53.jpg
frame_kill_103.jpg
frame_kill_70.jpg
frame_death_177.jpg
frame_kill_294.jpg
frame_death_282.jpg
frame_kill_80.jpg
frame_kill_221.jpg
frame_kill_150.jpg
frame_death_110.jpg
frame_kill_30.jpg
frame_death_54.jpg
frame_kill_233.jpg
frame_kill_198.jpg
frame_kill_43.jpg
frame_death_131.jpg
frame_kill_110.jpg
frame_kill_74.jpg
frame_kill_11.jpg
frame_death_29.jpg
frame_death_204.jpg
frame_death_139.jpg
frame_death_239.jpg
frame_death_262.jpg
frame_kill_62.jpg
frame_kill_201.jpg
frame_death_272.jpg
frame_death_6.jpg
frame_death_257.jpg
frame_death_121.jpg
frame_kill_167.jpg
frame_kill_126.jpg
frame_death_3.jpg
frame_death_253.jpg
frame_death_141.jpg
frame_kill_279.jpg
frame_kill_241.jpg
frame_death_171.jpg
frame_death_201.jpg
frame_death_203.jpg
frame_kill_171.jpg
frame_death_210.jpg
frame_death_278.jpg
frame_kill_148.jpg
frame_kill_205.jpg
frame_death_98.jpg
frame_kill_297.jpg
frame_death_22.jpg
frame_death_151.jpg
frame_kill_254.jpg
frame_death_251.jpg
frame_kill_65.jpg
frame_kill_94.jpg
frame_kill_118.jpg
frame_kill_266.jpg
frame_death_281.jpg
frame_kill_159.jpg
frame_kill_136.jpg
frame_kill_39.jpg
frame_death_55.jpg
frame_kill_199.jpg
frame_death_140.jpg
frame_death_221.jpg
frame_death_125.jpg
frame_death_60.jpg
frame_death_182.jpg
frame_death_86.jpg
frame_death_183.jpg
frame_death_290.jpg
frame_kill_190.jpg
frame_kill_24.jpg
frame_death_134.jpg
frame_kill_273.jpg
frame_death_158.jpg
frame_kill_71.jpg
frame_death_292.jpg
frame_kill_79.jpg
frame_death_14.jpg
frame_kill_37.jpg
frame_kill_36.jpg
frame_kill_17.jpg
frame_kill_264.jpg
frame_kill_7.jpg
frame_death_263.jpg
frame_death_104.jpg
frame_death_57.jpg
frame_death_108.jpg
frame_kill_151.jpg
frame_kill_68.jpg
frame_kill_170.jpg
frame_kill_57.jpg
frame_death_25.jpg
frame_death_107.jpg
frame_death_15.jpg
frame_kill_258.jpg
frame_kill_204.jpg
frame_kill_286.jpg
frame_kill_289.jpg
frame_death_32.jpg
frame_death_289.jpg
frame_death_288.jpg
frame_death_212.jpg
frame_death_46.jpg
frame_kill_130.jpg
frame_kill_173.jpg
frame_kill_272.jpg
frame_kill_298.jpg
frame_kill_189.jpg
frame_death_111.jpg
frame_kill_69.jpg
frame_kill_222.jpg
frame_death_19.jpg
frame_death_190.jpg
frame_kill_226.jpg
frame_kill_168.jpg
frame_kill_106.jpg
frame_death_234.jpg
frame_kill_115.jpg
frame_kill_85.jpg
frame_death_143.jpg
frame_kill_271.jpg
frame_kill_99.jpg
frame_kill_240.jpg
frame_death_149.jpg
frame_kill_87.jpg
frame_kill_98.jpg
frame_death_207.jpg
frame_death_255.jpg
frame_death_167.jpg
frame_death_11.jpg
frame_death_115.jpg
frame_kill_269.jpg
frame_kill_237.jpg
frame_kill_251.jpg
frame_death_268.jpg
frame_kill_139.jpg
frame_kill_285.jpg
frame_kill_188.jpg
frame_death_270.jpg
frame_kill_19.jpg
frame_kill_206.jpg
frame_kill_218.jpg
frame_death_133.jpg
frame_kill_3.jpg
frame_kill_192.jpg
frame_kill_165.jpg
frame_death_214.jpg
frame_kill_2.jpg
frame_kill_249.jpg
frame_kill_217.jpg
frame_kill_128.jpg
frame_death_237.jpg
frame_death_155.jpg
frame_kill_107.jpg
frame_death_286.jpg
frame_death_294.jpg
frame_kill_105.jpg
frame_kill_1.jpg
frame_death_215.jpg
frame_death_273.jpg
frame_death_106.jpg
frame_death_30.jpg
frame_death_194.jpg
frame_kill_127.jpg
frame_kill_6.jpg
frame_kill_34.jpg
frame_death_260.jpg
frame_kill_29.jpg
frame_death_97.jpg
frame_death_66.jpg
frame_kill_82.jpg
frame_kill_18.jpg
frame_death_7.jpg
frame_death_297.jpg
frame_kill_172.jpg
frame_death_162.jpg
frame_death_63.jpg
frame_kill_194.jpg
frame_death_26.jpg
frame_death_192.jpg
frame_death_90.jpg
frame_death_209.jpg
frame_death_265.jpg
frame_death_271.jpg
frame_kill_219.jpg
frame_kill_265.jpg
frame_death_83.jpg
frame_death_280.jpg
frame_death_223.jpg
frame_kill_193.jpg
frame_kill_75.jpg
frame_death_69.jpg
frame_kill_53.jpg
frame_kill_154.jpg
frame_kill_125.jpg
frame_kill_160.jpg
frame_death_229.jpg
frame_death_256.jpg
frame_death_144.jpg
frame_death_189.jpg
frame_death_132.jpg
frame_death_299.jpg
frame_death_74.jpg
frame_kill_280.jpg
frame_kill_137.jpg
frame_death_61.jpg
frame_kill_182.jpg
frame_kill_104.jpg
frame_death_70.jpg
frame_kill_200.jpg
frame_death_178.jpg
frame_death_173.jpg
frame_kill_28.jpg
frame_death_208.jpg
frame_death_279.jpg
frame_kill_186.jpg
frame_death_218.jpg
frame_death_191.jpg
frame_death_169.jpg
frame_kill_92.jpg
frame_kill_242.jpg
frame_kill_284.jpg
frame_death_233.jpg
frame_kill_63.jpg
frame_kill_131.jpg
frame_death_114.jpg
frame_death_10.jpg
frame_kill_76.jpg
frame_kill_66.jpg
frame_kill_152.jpg
frame_kill_144.jpg
frame_death_77.jpg
frame_kill_141.jpg
frame_kill_213.jpg
frame_kill_195.jpg
frame_kill_89.jpg
frame_kill_296.jpg
frame_death_157.jpg
frame_kill_214.jpg
frame_kill_157.jpg
frame_death_202.jpg
frame_death_71.jpg
frame_death_181.jpg
frame_death_249.jpg
frame_kill_156.jpg
frame_kill_229.jpg
frame_death_148.jpg
frame_kill_211.jpg
frame_death_9.jpg
frame_death_220.jpg
frame_death_48.jpg
frame_kill_51.jpg
frame_death_187.jpg
frame_death_197.jpg
frame_kill_224.jpg
frame_kill_300.jpg
frame_kill_134.jpg
frame_kill_250.jpg
frame_death_243.jpg
frame_death_102.jpg
frame_kill_16.jpg
frame_death_199.jpg
frame_kill_84.jpg
frame_kill_227.jpg
frame_death_28.jpg
frame_kill_243.jpg
frame_death_164.jpg
frame_kill_262.jpg
frame_death_160.jpg
frame_kill_143.jpg
frame_death_17.jpg
frame_death_101.jpg
frame_death_150.jpg
frame_death_231.jpg
frame_death_36.jpg
frame_death_152.jpg
frame_kill_31.jpg
frame_death_174.jpg
frame_kill_47.jpg
frame_kill_161.jpg
frame_kill_256.jpg
frame_kill_124.jpg
frame_death_206.jpg
frame_kill_146.jpg
frame_kill_142.jpg
frame_kill_119.jpg
frame_death_153.jpg
frame_death_285.jpg
frame_kill_117.jpg
frame_kill_102.jpg
frame_kill_4.jpg
frame_death_180.jpg
frame_kill_72.jpg
frame_death_113.jpg
frame_death_137.jpg
frame_kill_239.jpg
frame_death_267.jpg
frame_kill_138.jpg
frame_kill_81.jpg
frame_death_79.jpg
frame_death_116.jpg
frame_kill_83.jpg
frame_kill_27.jpg
frame_death_38.jpg
frame_kill_91.jpg
frame_death_85.jpg
frame_kill_140.jpg
frame_death_196.jpg
frame_death_75.jpg
frame_death_247.jpg
frame_death_109.jpg
frame_kill_8.jpg
frame_death_184.jpg
frame_death_242.jpg
frame_kill_203.jpg
frame_kill_220.jpg
frame_death_135.jpg
frame_death_287.jpg
frame_death_68.jpg
frame_kill_277.jpg
frame_kill_46.jpg
frame_death_51.jpg
frame_kill_20.jpg
frame_death_99.jpg
frame_kill_244.jpg
frame_kill_207.jpg
frame_kill_109.jpg
frame_death_205.jpg
frame_kill_232.jpg
frame_death_165.jpg
frame_kill_275.jpg
frame_kill_212.jpg
frame_death_119.jpg
frame_kill_180.jpg
frame_death_172.jpg
frame_kill_292.jpg
frame_kill_45.jpg
frame_kill_210.jpg
frame_death_16.jpg
frame_kill_33.jpg
frame_kill_230.jpg
frame_death_52.jpg
frame_death_12.jpg
frame_death_127.jpg
frame_death_43.jpg
frame_death_277.jpg
frame_death_88.jpg
frame_kill_10.jpg
frame_death_283.jpg
frame_death_40.jpg
frame_kill_135.jpg
frame_death_50.jpg
frame_kill_129.jpg
frame_kill_175.jpg
frame_kill_59.jpg
frame_kill_223.jpg
frame_death_228.jpg
frame_death_91.jpg
frame_death_224.jpg
frame_death_230.jpg
frame_death_261.jpg
frame_kill_225.jpg
frame_kill_26.jpg
frame_death_245.jpg
frame_kill_202.jpg
frame_death_170.jpg
frame_kill_293.jpg
frame_kill_40.jpg
frame_kill_278.jpg
frame_kill_23.jpg
frame_kill_197.jpg
frame_kill_209.jpg
frame_death_269.jpg
frame_kill_95.jpg
frame_death_250.jpg
frame_death_56.jpg
frame_kill_179.jpg
frame_kill_112.jpg
frame_kill_111.jpg
frame_death_244.jpg
frame_death_120.jpg
frame_death_65.jpg
frame_kill_181.jpg
frame_kill_38.jpg
frame_death_213.jpg
frame_kill_163.jpg
frame_kill_97.jpg
frame_death_72.jpg
frame_death_276.jpg
frame_kill_158.jpg
frame_kill_270.jpg
frame_kill_88.jpg
frame_death_240.jpg
frame_death_266.jpg
frame_death_117.jpg
frame_death_291.jpg
frame_kill_22.jpg
frame_kill_215.jpg
frame_kill_78.jpg
frame_kill_248.jpg
frame_kill_231.jpg
frame_kill_50.jpg
frame_death_42.jpg
frame_death_146.jpg
frame_death_295.jpg
frame_death_136.jpg
frame_kill_56.jpg
frame_death_147.jpg
frame_death_248.jpg
frame_kill_235.jpg
frame_kill_295.jpg
frame_kill_86.jpg
frame_kill_236.jpg
frame_death_59.jpg
frame_death_300.jpg
frame_death_64.jpg
frame_death_124.jpg
frame_death_216.jpg
frame_kill_41.jpg
frame_death_225.jpg
frame_death_96.jpg
frame_death_93.jpg
frame_death_49.jpg
frame_death_161.jpg
frame_kill_287.jpg
frame_death_258.jpg
frame_kill_21.jpg
frame_kill_164.jpg
frame_death_142.jpg
frame_kill_123.jpg
frame_death_235.jpg
frame_death_138.jpg
frame_death_154.jpg
frame_death_236.jpg
frame_death_41.jpg
frame_kill_267.jpg
frame_death_1.jpg
frame_kill_228.jpg
frame_death_82.jpg
frame_death_20.jpg
frame_death_13.jpg
frame_kill_121.jpg
frame_death_159.jpg
frame_death_100.jpg
frame_kill_60.jpg
frame_kill_120.jpg
frame_death_44.jpg
frame_kill_48.jpg
frame_kill_187.jpg
frame_kill_132.jpg
frame_death_67.jpg
frame_death_200.jpg
frame_kill_288.jpg
frame_death_81.jpg
frame_death_130.jpg
frame_kill_252.jpg
frame_death_18.jpg
frame_kill_67.jpg
frame_kill_245.jpg
frame_death_284.jpg
frame_kill_13.jpg
frame_death_128.jpg
frame_kill_114.jpg
frame_death_222.jpg
frame_death_198.jpg
frame_kill_162.jpg
frame_death_226.jpg
frame_death_4.jpg
frame_death_175.jpg
frame_death_2.jpg

In [13]:
from keras.preprocessing import image

In [533]:
train_set_lst = []
i=0

for video_name in train_set['videos']:
    i+=1
    print(i)
    img = image.load_img(video_name, target_size=(224,224,3))
    img = image.img_to_array(img)
    img = img/255
    train_set_lst.append(img)
    train_set_array = np.array(train_set_lst)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600

In [535]:
val_set_lst = []
i=0

for video_name in val_set['videos']:
    i+=1
    img = image.load_img(video_name, target_size=(224,224,3))
    img = image.img_to_array(img)
    img = img/255
    val_set_lst.append(img)
    val_set_array = np.array(val_set_lst)
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200

In [536]:
test_set_lst = []
i=0

for video_name in test_set['videos']:
    i+=1
    img = image.load_img(video_name, target_size=(224,224,3))
    img = image.img_to_array(img)
    img = img/255
    test_set_lst.append(img)
    test_set_array = np.array(test_set_lst)
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200

In [537]:
print(train_set_array.shape)
print(val_set_array.shape)
print(test_set_array.shape)

(600, 224, 224, 3)
(200, 224, 224, 3)
(200, 224, 224, 3)

In [538]:
import keras
from keras.models import Sequential
from keras.applications.vgg16 import VGG16
from keras.layers import Dense, InputLayer, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, GlobalMaxPooling2D

In [539]:
base_model = VGG16(weights='imagenet', include_top=False)

In [540]:
X_train = base_model.predict(train_set_array)

X_train.shape

(600, 7, 7, 512)

In [541]:
X_val = base_model.predict(val_set_array)

X_val.shape

(200, 7, 7, 512)

In [542]:
X_test = base_model.predict(test_set_array)
X_test.shape

(200, 7, 7, 512)

In [543]:
"Warning"
#X_train_copy = X_train
#X_val_copy = X_val
#X_test_copy = X_test

In [642]:
X_train = X_train_copy
X_val = X_val_copy
X_test = X_test_copy

In [643]:
X_train = X_train.reshape(X_train.shape[0], 7*7*512)
X_val = X_val.reshape(X_val.shape[0], 7*7*512)
X_test = X_val.reshape(X_val.shape[0], 7*7*512)
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(600, 25088)
(200, 25088)
(200, 25088)

In [629]:
max = X_train.max()
X_train = X_train/max
X_val = X_val/max

In [635]:
model = Sequential()
model.add(Dense(2028, activation='relu', input_shape=(25088,)))
model.add(Dropout(0.1))
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(2, activation='softmax'))

In [644]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(25088,)))
model.add(Dropout(0.5))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(74, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))

In [436]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_65 (Dense)             (None, 1024)              25691136
_________________________________________________________________
dropout_52 (Dropout)         (None, 1024)              0
_________________________________________________________________
dense_66 (Dense)             (None, 512)               524800
_________________________________________________________________
dropout_53 (Dropout)         (None, 512)               0
_________________________________________________________________
dense_67 (Dense)             (None, 256)               131328
_________________________________________________________________
dropout_54 (Dropout)         (None, 256)               0
_________________________________________________________________
dense_68 (Dense)             (None, 128)               32896
_________________________________________________________________
dropout_55 (Dropout)         (None, 128)               0
_________________________________________________________________
dense_69 (Dense)             (None, 2)                 258
=================================================================
Total params: 26,380,418
Trainable params: 26,380,418
Non-trainable params: 0
_________________________________________________________________

In [645]:
from keras.callbacks import ModelCheckpoint
mcp_save = ModelCheckpoint('weight.hdf5', save_best_only=True, monitor='val_loss', mode='min')

In [646]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [95]:
#y_train = np.array(y_train)
#y_val = np.array(y_val)

#y_train = y_train.reshape(600,1)
#y_val = y_val.reshape(200,1)

In [430]:
y_train

     label_kill  label_death
557           0            1
270           1            0
464           0            1
215           1            0
392           0            1
..          ...          ...
52            1            0
189           1            0
283           1            0
443           0            1
532           0            1

[600 rows x 2 columns]

In [647]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val), callbacks=[mcp_save], batch_size=75)

Epoch 1/50
8/8 [==============================] - 3s 232ms/step - loss: 2.0621 - accuracy: 0.5052 - val_loss: 0.7230 - val_accuracy: 0.5000
Epoch 2/50
8/8 [==============================] - 1s 141ms/step - loss: 2.2774 - accuracy: 0.5198 - val_loss: 0.6263 - val_accuracy: 0.7100
Epoch 3/50
8/8 [==============================] - 1s 139ms/step - loss: 1.3190 - accuracy: 0.5747 - val_loss: 0.5934 - val_accuracy: 0.8850
Epoch 4/50
8/8 [==============================] - 1s 141ms/step - loss: 1.0865 - accuracy: 0.5692 - val_loss: 0.5829 - val_accuracy: 0.8950
Epoch 5/50
8/8 [==============================] - 1s 141ms/step - loss: 0.8226 - accuracy: 0.5369 - val_loss: 0.5654 - val_accuracy: 0.8750
Epoch 6/50
8/8 [==============================] - 1s 142ms/step - loss: 0.7245 - accuracy: 0.5717 - val_loss: 0.5748 - val_accuracy: 0.8900
Epoch 7/50
8/8 [==============================] - 1s 150ms/step - loss: 0.6577 - accuracy: 0.5958 - val_loss: 0.5714 - val_accuracy: 0.8800
Epoch 8/50
8/8 [==============================] - 1s 140ms/step - loss: 0.6595 - accuracy: 0.6374 - val_loss: 0.5241 - val_accuracy: 0.8900
Epoch 9/50
8/8 [==============================] - 1s 143ms/step - loss: 0.5982 - accuracy: 0.6363 - val_loss: 0.5237 - val_accuracy: 0.8700
Epoch 10/50
8/8 [==============================] - 1s 151ms/step - loss: 0.6081 - accuracy: 0.6604 - val_loss: 0.4629 - val_accuracy: 0.8950
Epoch 11/50
8/8 [==============================] - 1s 144ms/step - loss: 0.5272 - accuracy: 0.7339 - val_loss: 0.3875 - val_accuracy: 0.8700
Epoch 12/50
8/8 [==============================] - 1s 146ms/step - loss: 0.4955 - accuracy: 0.7515 - val_loss: 0.3683 - val_accuracy: 0.8950
Epoch 13/50
8/8 [==============================] - 1s 147ms/step - loss: 0.4753 - accuracy: 0.7555 - val_loss: 0.3593 - val_accuracy: 0.8500
Epoch 14/50
8/8 [==============================] - 1s 145ms/step - loss: 0.4676 - accuracy: 0.7600 - val_loss: 0.2829 - val_accuracy: 0.9050
Epoch 15/50
8/8 [==============================] - 1s 145ms/step - loss: 0.4228 - accuracy: 0.7972 - val_loss: 0.3149 - val_accuracy: 0.9200
Epoch 16/50
8/8 [==============================] - 1s 145ms/step - loss: 0.3726 - accuracy: 0.8229 - val_loss: 0.2156 - val_accuracy: 0.9300
Epoch 17/50
8/8 [==============================] - 1s 179ms/step - loss: 0.3747 - accuracy: 0.8461 - val_loss: 0.2656 - val_accuracy: 0.9000
Epoch 18/50
8/8 [==============================] - 1s 168ms/step - loss: 0.3432 - accuracy: 0.8366 - val_loss: 0.2120 - val_accuracy: 0.9300
Epoch 19/50
8/8 [==============================] - 1s 176ms/step - loss: 0.2712 - accuracy: 0.8822 - val_loss: 0.1964 - val_accuracy: 0.9250
Epoch 20/50
8/8 [==============================] - 1s 168ms/step - loss: 0.2415 - accuracy: 0.8881 - val_loss: 0.1818 - val_accuracy: 0.9450
Epoch 21/50
8/8 [==============================] - 1s 165ms/step - loss: 0.2437 - accuracy: 0.8927 - val_loss: 0.1823 - val_accuracy: 0.9200
Epoch 22/50
8/8 [==============================] - 1s 164ms/step - loss: 0.2391 - accuracy: 0.8969 - val_loss: 0.1535 - val_accuracy: 0.9500
Epoch 23/50
8/8 [==============================] - 1s 162ms/step - loss: 0.2360 - accuracy: 0.9003 - val_loss: 0.1806 - val_accuracy: 0.9350
Epoch 24/50
8/8 [==============================] - 1s 141ms/step - loss: 0.1944 - accuracy: 0.9260 - val_loss: 0.1751 - val_accuracy: 0.9300
Epoch 25/50
8/8 [==============================] - 1s 143ms/step - loss: 0.1327 - accuracy: 0.9520 - val_loss: 0.1956 - val_accuracy: 0.9350
Epoch 26/50
8/8 [==============================] - 1s 143ms/step - loss: 0.1483 - accuracy: 0.9410 - val_loss: 0.1939 - val_accuracy: 0.9250
Epoch 27/50
8/8 [==============================] - 1s 142ms/step - loss: 0.1461 - accuracy: 0.9456 - val_loss: 0.2478 - val_accuracy: 0.9300
Epoch 28/50
8/8 [==============================] - 1s 149ms/step - loss: 0.1194 - accuracy: 0.9503 - val_loss: 0.1745 - val_accuracy: 0.9450
Epoch 29/50
8/8 [==============================] - 1s 153ms/step - loss: 0.0988 - accuracy: 0.9666 - val_loss: 0.2495 - val_accuracy: 0.9350
Epoch 30/50
8/8 [==============================] - 1s 139ms/step - loss: 0.0905 - accuracy: 0.9634 - val_loss: 0.2281 - val_accuracy: 0.9150
Epoch 31/50
8/8 [==============================] - 1s 155ms/step - loss: 0.1442 - accuracy: 0.9223 - val_loss: 0.1922 - val_accuracy: 0.9250
Epoch 32/50
8/8 [==============================] - 1s 152ms/step - loss: 0.1236 - accuracy: 0.9491 - val_loss: 0.2398 - val_accuracy: 0.9250
Epoch 33/50
8/8 [==============================] - 1s 138ms/step - loss: 0.1047 - accuracy: 0.9535 - val_loss: 0.3793 - val_accuracy: 0.9250
Epoch 34/50
8/8 [==============================] - 1s 149ms/step - loss: 0.1246 - accuracy: 0.9471 - val_loss: 0.1996 - val_accuracy: 0.9400
Epoch 35/50
8/8 [==============================] - 1s 146ms/step - loss: 0.0822 - accuracy: 0.9603 - val_loss: 0.3185 - val_accuracy: 0.9200
Epoch 36/50
8/8 [==============================] - 1s 148ms/step - loss: 0.1133 - accuracy: 0.9532 - val_loss: 0.2701 - val_accuracy: 0.9300
Epoch 37/50
8/8 [==============================] - 1s 142ms/step - loss: 0.1256 - accuracy: 0.9403 - val_loss: 0.1535 - val_accuracy: 0.9450
Epoch 38/50
8/8 [==============================] - 2s 205ms/step - loss: 0.1115 - accuracy: 0.9494 - val_loss: 0.2434 - val_accuracy: 0.9300
Epoch 39/50
8/8 [==============================] - 2s 208ms/step - loss: 0.0954 - accuracy: 0.9632 - val_loss: 0.1886 - val_accuracy: 0.9500
Epoch 40/50
8/8 [==============================] - 1s 168ms/step - loss: 0.0828 - accuracy: 0.9620 - val_loss: 0.1746 - val_accuracy: 0.9550
Epoch 41/50
8/8 [==============================] - 1s 178ms/step - loss: 0.0807 - accuracy: 0.9674 - val_loss: 0.3713 - val_accuracy: 0.9400
Epoch 42/50
8/8 [==============================] - 1s 182ms/step - loss: 0.0624 - accuracy: 0.9699 - val_loss: 0.3209 - val_accuracy: 0.9300
Epoch 43/50
8/8 [==============================] - 2s 200ms/step - loss: 0.0542 - accuracy: 0.9774 - val_loss: 0.1569 - val_accuracy: 0.9550
Epoch 44/50
8/8 [==============================] - 1s 174ms/step - loss: 0.0999 - accuracy: 0.9541 - val_loss: 0.2322 - val_accuracy: 0.9100
Epoch 45/50
8/8 [==============================] - 1s 175ms/step - loss: 0.0980 - accuracy: 0.9531 - val_loss: 0.3115 - val_accuracy: 0.9150
Epoch 46/50
8/8 [==============================] - 1s 169ms/step - loss: 0.0793 - accuracy: 0.9700 - val_loss: 0.3327 - val_accuracy: 0.9400
Epoch 47/50
8/8 [==============================] - 2s 231ms/step - loss: 0.0944 - accuracy: 0.9578 - val_loss: 0.2286 - val_accuracy: 0.9400
Epoch 48/50
8/8 [==============================] - 1s 165ms/step - loss: 0.0692 - accuracy: 0.9684 - val_loss: 0.3523 - val_accuracy: 0.9200
Epoch 49/50
8/8 [==============================] - 1s 156ms/step - loss: 0.0691 - accuracy: 0.9605 - val_loss: 0.4386 - val_accuracy: 0.9150
Epoch 50/50
8/8 [==============================] - 1s 153ms/step - loss: 0.1322 - accuracy: 0.9543 - val_loss: 0.1764 - val_accuracy: 0.9450

In [ ]:
prediction = model.predict(X_test)
prediction

y_test_1d = y_test.to_numpy()

def maxfunction(x):
        return np.argmax(x)

pred_1d = np.apply_along_axis( maxfunction, axis=1, arr=prediction )

y_test_1d = np.apply_along_axis( maxfunction, axis=1, arr=y_test_1d )

print(accuracy_score(y_test_1d, pred_1d)*100)

In [49]:
model.save_weights('weight.hdf5')

In [ ]:
def final_predict(get_video):
    def frame_no(video_name):
        cap= cv2.VideoCapture(video_name)
        i=0
        while(cap.isOpened()):
            ret, frame = cap.read()
            if ret == False:
                break

            frameId = cap.get(1)

        #cap.release()
        #cv2.destroyAllWindows()
        return frameId

    j=1
    video_name = get_video
    predict_lst = []

    cap= cv2.VideoCapture(video_name)
    frame_needed = 6
    #frameRate = cap.get(5)
    tot_frame = frame_no(video_name)
    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret == False:
            break
        frameId = cap.get(1)

        a = np.linspace(0, tot_frame, frame_needed)

        for i in range(len(a)):
            if (frameId == math.floor(a[i])):
                cv2.imwrite('predict'+str(j)+'.jpg',frame)
                predict_lst.append('predict'+str(j)+'.jpg')
                j+=1

    cap.release()
    cv2.destroyAllWindows()

    predict_set_lst = []
    for i in predict_lst:
        img = image.load_img(i, target_size=(224,224,3))
        img = image.img_to_array(img)
        img = img/255
        predict_set_lst.append(img)
        predict_set_array = np.array(predict_set_lst)

    predict_final = base_model.predict(predict_set_array)
    predict_final = predict_final.reshape(predict_final.shape[0],7*7*512)
    prediction = model.predict(predict_final)

    def maxfunction(x):
        return np.argmax(x)

    a = np.apply_along_axis( maxfunction, axis=1, arr=prediction )
    print(a)

    s = sum(a)
    if s>=3:
        print('Death')
    else: 
        print('Kill')

In [650]:
final_predict(r'C:\Users\Oitijjho\Desktop\Project 101\kill_70.mp4')

[0 0 0 0 0]
Kill

In [497]:
prediction = model.predict(X_test)
prediction

array([[1.58869472e-04, 9.99841094e-01],
       [7.87540138e-01, 2.12459847e-01],
       [8.64743769e-01, 1.35256231e-01],
       [3.82386497e-04, 9.99617577e-01],
       [1.56377588e-04, 9.99843597e-01],
       [8.55523765e-01, 1.44476250e-01],
       [2.57894746e-04, 9.99742091e-01],
       [9.16533232e-01, 8.34667981e-02],
       [9.09872237e-04, 9.99090075e-01],
       [9.17289615e-01, 8.27104002e-02],
       [9.00680840e-01, 9.93192047e-02],
       [6.91878377e-04, 9.99308109e-01],
       [1.28304542e-04, 9.99871731e-01],
       [4.50273074e-04, 9.99549687e-01],
       [5.25925134e-04, 9.99474108e-01],
       [5.67681331e-04, 9.99432266e-01],
       [6.19607091e-01, 3.80392939e-01],
       [8.84100497e-01, 1.15899540e-01],
       [3.08318384e-04, 9.99691725e-01],
       [9.04949069e-01, 9.50509980e-02],
       [5.42741094e-04, 9.99457300e-01],
       [5.55906328e-04, 9.99444067e-01],
       [3.12650984e-04, 9.99687314e-01],
       [8.74010801e-01, 1.25989199e-01],
       [7.31485197e-05, 9.99926805e-01],
       [1.10664980e-04, 9.99889374e-01],
       [5.47442469e-04, 9.99452531e-01],
       [1.94853125e-03, 9.98051524e-01],
       [7.31721520e-04, 9.99268234e-01],
       [5.82742563e-04, 9.99417305e-01],
       [4.82250797e-03, 9.95177507e-01],
       [8.80572379e-01, 1.19427621e-01],
       [8.61349940e-01, 1.38650045e-01],
       [4.43624245e-04, 9.99556363e-01],
       [5.55048580e-04, 9.99444902e-01],
       [8.88254225e-01, 1.11745819e-01],
       [8.00304348e-04, 9.99199688e-01],
       [8.23649345e-04, 9.99176323e-01],
       [6.90929830e-01, 3.09070170e-01],
       [9.15304482e-01, 8.46955478e-02],
       [1.81045354e-04, 9.99818981e-01],
       [1.20536913e-03, 9.98794556e-01],
       [5.26700402e-04, 9.99473274e-01],
       [7.79395268e-05, 9.99922037e-01],
       [1.83130789e-03, 9.98168707e-01],
       [4.32852568e-04, 9.99567091e-01],
       [4.38202987e-04, 9.99561727e-01],
       [5.58155007e-04, 9.99441803e-01],
       [1.04023819e-03, 9.98959780e-01],
       [1.35259237e-03, 9.98647392e-01],
       [4.47103994e-05, 9.99955297e-01],
       [3.30841809e-04, 9.99669194e-01],
       [3.45970824e-04, 9.99654055e-01],
       [1.58047269e-03, 9.98419523e-01],
       [3.76322598e-04, 9.99623656e-01],
       [8.49323332e-01, 1.50676638e-01],
       [5.72136641e-01, 4.27863359e-01],
       [8.00026655e-02, 9.19997275e-01],
       [8.99092993e-04, 9.99100924e-01],
       [2.52511760e-04, 9.99747455e-01],
       [9.24489081e-01, 7.55109265e-02],
       [8.53307128e-01, 1.46692887e-01],
       [4.55125584e-04, 9.99544799e-01],
       [3.93713883e-04, 9.99606311e-01],
       [2.07849793e-04, 9.99792159e-01],
       [2.50991201e-04, 9.99749005e-01],
       [8.42628539e-01, 1.57371491e-01],
       [6.68567256e-04, 9.99331474e-01],
       [8.72987926e-01, 1.27012059e-01],
       [8.75837445e-01, 1.24162517e-01],
       [2.17590044e-04, 9.99782383e-01],
       [9.97029361e-04, 9.99002993e-01],
       [4.52934997e-04, 9.99547064e-01],
       [2.07522462e-04, 9.99792516e-01],
       [3.27721442e-04, 9.99672294e-01],
       [9.08172879e-05, 9.99909163e-01],
       [2.26531542e-04, 9.99773443e-01],
       [1.82356674e-03, 9.98176455e-01],
       [9.08592761e-01, 9.14072543e-02],
       [7.53029943e-01, 2.46970057e-01],
       [8.50096520e-04, 9.99149919e-01],
       [8.97328794e-01, 1.02671213e-01],
       [5.42633329e-03, 9.94573653e-01],
       [6.44111424e-04, 9.99355853e-01],
       [7.73423380e-05, 9.99922633e-01],
       [7.48549181e-04, 9.99251425e-01],
       [8.02750587e-01, 1.97249427e-01],
       [1.93925982e-04, 9.99806106e-01],
       [3.64159321e-04, 9.99635816e-01],
       [8.44884038e-01, 1.55115902e-01],
       [8.78465712e-01, 1.21534325e-01],
       [2.20318139e-03, 9.97796893e-01],
       [1.90488339e-04, 9.99809563e-01],
       [4.01375641e-04, 9.99598682e-01],
       [8.63740325e-01, 1.36259705e-01],
       [2.29025798e-04, 9.99770939e-01],
       [1.29448762e-03, 9.98705506e-01],
       [1.37610454e-03, 9.98623848e-01],
       [6.12305641e-01, 3.87694329e-01],
       [5.04394120e-04, 9.99495625e-01],
       [9.17527199e-01, 8.24728534e-02],
       [4.07342421e-04, 9.99592721e-01],
       [6.39536858e-01, 3.60463172e-01],
       [1.18952827e-03, 9.98810530e-01],
       [8.86690974e-01, 1.13309093e-01],
       [7.07881272e-01, 2.92118758e-01],
       [9.06075176e-04, 9.99093890e-01],
       [3.11526324e-04, 9.99688506e-01],
       [2.85744201e-04, 9.99714196e-01],
       [6.54083269e-04, 9.99345958e-01],
       [7.62857258e-01, 2.37142742e-01],
       [3.84504063e-04, 9.99615431e-01],
       [8.03249359e-01, 1.96750596e-01],
       [7.53995671e-04, 9.99246001e-01],
       [1.74774497e-04, 9.99825299e-01],
       [6.37749559e-04, 9.99362290e-01],
       [1.42936755e-04, 9.99857068e-01],
       [2.39867508e-01, 7.60132492e-01],
       [1.53366610e-01, 8.46633375e-01],
       [4.79719572e-04, 9.99520302e-01],
       [8.77566278e-01, 1.22433670e-01],
       [3.62265133e-03, 9.96377409e-01],
       [1.70929328e-04, 9.99829054e-01],
       [6.37630466e-04, 9.99362409e-01],
       [5.85953938e-04, 9.99414086e-01],
       [6.40178740e-04, 9.99359787e-01],
       [2.82129535e-04, 9.99717891e-01],
       [3.76216951e-04, 9.99623775e-01],
       [3.00726184e-04, 9.99699354e-01],
       [8.24301243e-01, 1.75698712e-01],
       [5.70859527e-04, 9.99429166e-01],
       [1.16908639e-04, 9.99883056e-01],
       [6.05158217e-04, 9.99394774e-01],
       [1.67256905e-04, 9.99832749e-01],
       [3.29606439e-04, 9.99670386e-01],
       [1.64997939e-04, 9.99835014e-01],
       [3.38572019e-04, 9.99661446e-01],
       [1.89447962e-03, 9.98105526e-01],
       [8.93629551e-01, 1.06370442e-01],
       [2.09166887e-04, 9.99790847e-01],
       [7.88343728e-01, 2.11656258e-01],
       [3.74560773e-01, 6.25439227e-01],
       [7.58217648e-04, 9.99241829e-01],
       [6.00737345e-04, 9.99399304e-01],
       [3.64066625e-04, 9.99635935e-01],
       [8.76762748e-01, 1.23237327e-01],
       [8.97640824e-01, 1.02359205e-01],
       [8.98222923e-01, 1.01777084e-01],
       [9.04168606e-01, 9.58313942e-02],
       [9.10663009e-01, 8.93369690e-02],
       [9.06766534e-01, 9.32334810e-02],
       [3.51256371e-04, 9.99648690e-01],
       [5.02390845e-04, 9.99497652e-01],
       [8.70254636e-01, 1.29745394e-01],
       [7.23238802e-04, 9.99276817e-01],
       [9.64939245e-04, 9.99035120e-01],
       [7.31621742e-01, 2.68378228e-01],
       [3.23845656e-04, 9.99676228e-01],
       [6.05289578e-01, 3.94710362e-01],
       [8.55863035e-01, 1.44137010e-01],
       [9.08911943e-01, 9.10881311e-02],
       [8.61734516e-05, 9.99913812e-01],
       [7.63826101e-05, 9.99923587e-01],
       [2.91415898e-04, 9.99708593e-01],
       [3.12264339e-04, 9.99687791e-01],
       [1.50867752e-04, 9.99849081e-01],
       [2.71899422e-04, 9.99728143e-01],
       [6.06504735e-04, 9.99393463e-01],
       [8.46646547e-01, 1.53353378e-01],
       [4.23067948e-03, 9.95769382e-01],
       [9.65575571e-04, 9.99034405e-01],
       [1.33291620e-03, 9.98667121e-01],
       [3.52947027e-05, 9.99964714e-01],
       [9.06876624e-01, 9.31233391e-02],
       [6.83127961e-04, 9.99316931e-01],
       [7.92672654e-05, 9.99920726e-01],
       [1.60363945e-03, 9.98396337e-01],
       [1.71302629e-04, 9.99828696e-01],
       [4.35339171e-04, 9.99564707e-01],
       [8.32118034e-01, 1.67881951e-01],
       [1.40955287e-03, 9.98590410e-01],
       [6.17328857e-04, 9.99382615e-01],
       [7.76799440e-01, 2.23200589e-01],
       [8.03070188e-01, 1.96929753e-01],
       [9.17016387e-01, 8.29836503e-02],
       [4.64410638e-04, 9.99535561e-01],
       [4.81852476e-04, 9.99518156e-01],
       [8.53276074e-01, 1.46723941e-01],
       [1.75824185e-04, 9.99824226e-01],
       [7.79835880e-01, 2.20164120e-01],
       [1.37493806e-03, 9.98625040e-01],
       [8.78655483e-05, 9.99912143e-01],
       [7.88639963e-01, 2.11360052e-01],
       [7.27191567e-04, 9.99272764e-01],
       [9.59045792e-05, 9.99904037e-01],
       [3.19163431e-04, 9.99680877e-01],
       [8.62009287e-01, 1.37990698e-01],
       [3.24427290e-03, 9.96755660e-01],
       [5.62002424e-05, 9.99943852e-01],
       [3.98539298e-04, 9.99601424e-01]], dtype=float32)

In [499]:
a.shape

(200,)

In [504]:
y_arr = y_test.to_numpy()
y_arr.shape

(200, 2)

In [506]:
def maxfunction(x):
        return np.argmax(x)

b = np.apply_along_axis( maxfunction, axis=1, arr=y_arr )
print(b)

[0 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1
 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0
 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 1
 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0
 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0
 1 1 1 1 0 0 0 1 0 1 1 0 1 1 1]

In [507]:
b.shape

(200,)

In [508]:
accuracy_score(a, b)*100

44.5

In [484]:
predict

['label_death']

In [479]:
type(y_test.columns.values)

numpy.ndarray

In [489]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)*100

ValueError: Classification metrics can't handle a mix of multilabel-indicator and binary targets

In [291]:
def frame_no(video_name):
    cap= cv2.VideoCapture(video_name)
    i=0
    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret == False:
            break
    
        frameId = cap.get(1)
    
    #cap.release()
    #cv2.destroyAllWindows()
    return frameId

In [465]:
j=1
video_name = r'C:\Users\Oitijjho\Desktop\Project 101\death_95.mp4'
predict_lst = []

cap= cv2.VideoCapture(video_name)
frame_needed = 6
#frameRate = cap.get(5)
tot_frame = frame_no(video_name)
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == False:
        break
    frameId = cap.get(1)

    a = np.linspace(0, tot_frame, frame_needed)

    for i in range(len(a)):
        if (frameId == math.floor(a[i])):
            cv2.imwrite('predict'+str(j)+'.jpg',frame)
            predict_lst.append('predict'+str(j)+'.jpg')
            j+=1
            
            


cap.release()
cv2.destroyAllWindows()

In [301]:
predict_lst

['predict1.jpg',
 'predict2.jpg',
 'predict3.jpg',
 'predict4.jpg',
 'predict5.jpg']

In [362]:
predict_set_lst = []
for i in predict_lst:
    img = image.load_img(i, target_size=(224,224,3))
    img = image.img_to_array(img)
    img = img/255
    predict_set_lst.append(img)
    predict_set_array = np.array(predict_set_lst)

In [363]:
predict_final = base_model.predict(predict_set_array)

In [323]:
predict_final.shape[0]

5

In [364]:
predict_final = predict_final.reshape(predict_final.shape[0],7*7*512)

In [326]:
predict_final.shape

(5, 25088)

In [365]:
prediction = model.predict(predict_final)
prediction

array([[7.9717365e-06, 9.9999201e-01],
       [3.8101523e-06, 9.9999619e-01],
       [3.1846632e-06, 9.9999678e-01],
       [1.3860966e-06, 9.9999857e-01],
       [4.7613688e-07, 9.9999952e-01]], dtype=float32)

In [328]:
prediction.shape

(5, 2)

In [366]:
def maxfunction(x):
    return np.argmax(x)

a = np.apply_along_axis( maxfunction, axis=1, arr=prediction )
print(a)

[1 1 1 1 1]

In [367]:
s = sum(a)
if s>=3:
    print('Death')
else: 
    print('Kill')

Death

In [466]:
def final_predict(get_video):
    def frame_no(video_name):
        cap= cv2.VideoCapture(video_name)
        i=0
        while(cap.isOpened()):
            ret, frame = cap.read()
            if ret == False:
                break

            frameId = cap.get(1)

        #cap.release()
        #cv2.destroyAllWindows()
        return frameId

    j=1
    video_name = get_video
    predict_lst = []

    cap= cv2.VideoCapture(video_name)
    frame_needed = 6
    #frameRate = cap.get(5)
    tot_frame = frame_no(video_name)
    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret == False:
            break
        frameId = cap.get(1)

        a = np.linspace(0, tot_frame, frame_needed)

        for i in range(len(a)):
            if (frameId == math.floor(a[i])):
                cv2.imwrite('predict'+str(j)+'.jpg',frame)
                predict_lst.append('predict'+str(j)+'.jpg')
                j+=1

    cap.release()
    cv2.destroyAllWindows()

    predict_set_lst = []
    for i in predict_lst:
        img = image.load_img(i, target_size=(224,224,3))
        img = image.img_to_array(img)
        img = img/255
        predict_set_lst.append(img)
        predict_set_array = np.array(predict_set_lst)

    predict_final = base_model.predict(predict_set_array)
    predict_final = predict_final.reshape(predict_final.shape[0],7*7*512)
    prediction = model.predict(predict_final)

    def maxfunction(x):
        return np.argmax(x)

    a = np.apply_along_axis( maxfunction, axis=1, arr=prediction )
    print(a)

    s = sum(a)
    if s>=3:
        print('Death')
    else: 
        print('Kill')

In [470]:
final_predict(r'C:\Users\Oitijjho\Desktop\Project 101\kill_90.mp4')

[1 1 1 1 1]
Death